### ISSUE TITLE
Concept for test data management

### ISSUE THREAD

**Issue by Max-Goebel** [oasp/oasp4j#153]
Currently there is no standardized concept for managing test data in OASP applications. There must be answers for the following questions:
**1. Should test data be shared by multiple test cases, or should each test case use its own data? Maybe there are different answers for master data and for transaction data.**
**2. How is the test object reset to a defined starting state, so that test cases can be run? Possible solutions:**
   a) Each test case must create its own test data (and remove it after having been run). 
   b) There is a monolithic data creation script for all test cases (and a corresponding data removal  script)
   c) Hybrid: Data that is used by multiple test cases is created and removed by common scripts, all test case specific data is created and removed by the individual test cases
**3. How do test cases / scripts create and remove data?**
   a) Via the service layer? 
   b) Via the logic layer?
   c) Via data access layer?
   d) Via SQL-Statements without using any layer?
   e) Via importing a database dump?
**4. In which format should test data be stored?**
   a) Interlinked objects, generated with dependency injection defined in spring xml?
   b) Separate files (CSV, XML…)?
   c) Hard coded in JUnit-Tests?
**5. Is it better to use synthetic data or should productive data be use, wherever it is possible?**
**6. Should there be a central data base pool for all test levels (also test levels that are not in responsibility of the developers) or should be separate test data pools per test level?**
**7. How should test data be generated?**
   a) No generation, only manual creation?
   b) “Throw-away-generation”. Generation scripts are not kept after data is generated
   c) Smart, configuratable generation tools? Which tools?
**8. How do we treat test data aging (e.g. date-fields that the system validates against the current system time)? Which wildcards are needed?**
**9. When do we update test data that is aged?**
   a) Automated data update before tests are started
   b) On-the-fly update by each test case

Maybe there are no general answers to all of these questions. At least it must be possible to give advice, in which cases which solution is the best. Furthermore, tool support is needed for managing und generating test data.

**Comment by hohwille** [comment]
First of all we should separate master data from transaction data as you suggested.
As we are proposing KISS and address the 80%-90% projects it is suitable to assume that there is one set of master data that can evolve over the time (but we do not consider multi-tenancy or the like where we a totally different sets of master-data). For DDL and master-data we are using Flyway. Hence, we can consider this aspect as solved and we strongly recommend that master-data is immutable. 
Further we use a concept of reserved ID ranges with low IDs for master-data and initialize hibernate sequence currently in our sample with 1000000. So all transaction-data created at runtime will have IDs >= 1000000. We can reserve a range 500000 <= x < 1000000 for testdata. 
Then we could have a generic script to drop all testdata or all transaction-data created by a test-case but still we have to consider some issues with referential integrity.

My few cents on test-data needs as prerequisite for multiple test-cases:
Maintaining test-data in external formats related to the DDL/DB Schema (no matter if SQL, CSV or XML) is IMHO causing a lot of maintenance costs as the DDL of real-live projects evolves and test-data gets broken. A more stable way is therefore to use stable services of the application itself to create the data. If for performance reasons this might be too slow for nightly builds of integration test runs some SQL or whatever can be generated from that and committed. But if DDL changes it can be regenerated automatically.

Individual JUnits can simply hardcode simple values that they use as "test-data" (this is IMHO something totally different to prerequisite test-data to run test-cases on). However, if there are complex permutation tests for business rules or the like you shall consider using XLS(X) or CSV instead of hard-coding the data.

According to KISS we should recommend to use one set of test-data that is provided in advance before integration tests are started. If a project is more complex and requires different pools of test-data then it should find a solution for itself but in most cases this only makes the world complicated and can be avoided by a KISS approach.

Test data aging is also an interesting aspect. So far we have no use-case for that in our simple sample application but we might face that in the future (see issues for advanced usecases). We should first address the more urgent aspects before this one.

**Comment by Max-Goebel** [comment]
Hohwille and I had a discussion about this issue. We created a working hypothesis regarding **topic 2 (starting state)**: 
All data that belongs to the test cases' starting state must be contained in the database. Neither do test cases need to load data themselves nor must there be a monolithic script. All entities that are created by the test cases must have an ID < 1000000. Before tests start, all IDs lower than 10000000 must be deleted. Data that belongs to the starting state is populated via Flyway. How this should be done will be subject on further discussions.

**Comment by hohwille** [comment]
> All entities that are created by the test cases must have an ID < 1000000. Before tests start, all IDs lower than 10000000 must be deleted.

Vice-versa: Entities created by the software will use the hibernate sequence that is initialized with 1000000. All master-data and test-data has to use IDs lower than that. At the beginning of an integration test, all entities with an ID >= 1000000 can/shall be deleted to eliminate (potential) side effects of previous test-cases.

**Comment by hohwille** [comment]
We are using flyway with great success. However, currently in our sample app we have no clear separation of master-data and test-data. This is currently mixed in flyway "migration-scripts", what is actually dead wrong. We need to study flyway and find a way to mark scripts as test-only so that these are skipped in normal/productive systems and will only be inserted for test (and development).

**Comment by julianmetzler** [comment]
An easy approach for separation of master-data and test-data would be to define two locations e.g.:
src/main/resources/db/migrations,
src/main/resources/db/test-data
(recommanded by Axel Fontaine, founder of Flyway, in a [SO thread](http://stackoverflow.com/questions/23324952/how-to-test-flyway-migration))
And call flyways migrate method on both locations when running tests and only on the first when running the application.
This could even be done before execution of single tests where it is necessary to ensure a certain database state, either with the [flyway-test-extensions project](https://github.com/flyway/flyway-test-extensions) or might also be feasible with the current spring bean (DatabaseMigrator).

**Comment by Max-Goebel** [comment]
If it is possible to switch between both directories multiple times within a migration, this may be the right approach.

Given that there are these migration scripts:
* src/main/resources/db/migrations/V1_bla.sql
* src/main/resources/db/migrations/V2_blubb.sql
* src/main/resources/db/test-data/V1.1_bla-test.sql
* src/main/resources/db/migrations/V2.1_blubb-test.sql

Then the scripts must be executed in the following order, when applied on a test database:
* V1_bla.sql
* V1.1_bla-test.sql
* V2_blubb.sql
* V2.1_blubb-test.sql

Otherwise all test migration scripts must be reworked in the case of DDL-changes.

**Comment by julianmetzler** [comment]
Flyway searches for migrations in all defined locations and applies them in the order specified by the version. So this would work.

**Comment by julianmetzler** [comment]
The AbstractRestServiceTest clears the DB and migrates it to the newest available version, including the test-data, in its setup method (called before every test case). So all test classes extending the AbstractRestServiceTest have a clean DB with the test data contained at every test case.

**Comment by maihacke** [comment]
Just a comment about database cleanup.
In many complex scenarios you cannot rely on rollbacking mechanism provided by spring test for example. I would suggest a test not to cleanup data after run, but to implement tests cleaning up data before running the test. Deleting after test run makes failure analysis harder, since produced testdata is lost.

**Comment by hohwille** [comment]
@maihacke thanks. We discussed the same things in the telco on testing. I fully agree with you :+1:

**Comment by Max-Goebel** [comment]
This ticket is replaced by the following tickets:
[Database initialization for test](https://github.com/oasp/oasp4j/issues/216)
[Data driven test](https://github.com/oasp/oasp4j/issues/207)
[Data for testing against interfaces](https://github.com/oasp/oasp4j/issues/212)
