### ISSUE TITLE
sample: create separate state for drink of OrderPosition

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#159]
From #135 

> extend OrderPosition with an assigned cook (Long getCookId()), seperate state of Drink and Meal+SideDish (see #101)

The state separation has not yet been implemented.

**Comment by oelsabba** [comment]
Also related to #101:

what comes to my mind to achieve this separation, is that we need to separate Drinks from the OrderPositions drop down menu. In this case, we end up having drinks ordered separately and those ordered within an Offer, because the properties: mealState and sideDishState do not apply for separately ordered drinks. For example, "Cola" should not be a member of the current drop down menu anymore. The same applies for both Meal and SideDish as separate orders.

In my opinion, there are two possible solutions for this problem:

1- Having a table tracking offer Order positions and other tables for tracking separate order positions like meals, drinks and side dishes.
2 - Having a single tracking table and providing null values in case of separate drinks, meals and side dishes. 

What do you think?

**Comment by hohwille** [comment]
@oelsabba IMHO you misunderstood the data model. There is a product that can be either a drink, meal, or a side dish. None of these is available for order by itself.
Further, there is an offer that can be any (non-empty) combination of a drink, meal, and/or a side dish and combines them with a price. So you can order a single drink e.g. a cola if available as offer (e.g. for 1€) while you can also order a menu with burger, fries and cola available as offer and will get it cheaper than ordering the 3 items individually. That is a common concept in restaurants.

An OrderPosition is representing the ordering of an Offer within an Order. Therefore you need to be able to select any available offer in the drop-down. As already discussed in other tickets splitting an OrderPosition into 1-3 sub entities (OrderOfferPositon) is too complicated and not following KISS.
This is why we want to separate the state of the 1-3 offers as a separate state within OrderPostion. And drink is the first step to go as it is not prepared by the kitchen/cook.

**Comment by oelsabba** [comment]
@hohwille  Thanks for making things clearer. I got what you pointed out. However, IMHO I still think that achieving a state separation through creating three classes would be a better choice
(eventhough, it sounds more complicated).
This could be done by having a level of abstraction and extending it through many types. 

I guess having three states of (SideDish, Drink and Meal) all contained within OrderPposition will lead to violating the OCP and will lead us to handling many null values. Furthermore, a class like `UcManageOrderPositionImpl` will grow very large and smelly, where we have to verify every possible state change and to derive the OrderPositionState change through many invidual state changes. 
Eventually we will need to establish many test scenarios achieve a higher test coverage. I don't know, but this is just MHO.

**Comment by hohwille** [comment]
Thanks for your feedback. However, you need to be aware that even if you create 3 additional sub-objects, you still need the OrderPosition (to track and bill the actual offer that has been ordered) and still have the same problem with different states. Instead of a state being null you will then have a "OrderOfferPosition" being "null". So in the end I am not totally sure if this would make it any easier. You would just wrap the additional state into an additional entity making queries and logic more complex.

We can however, discuss if we should immediately introduce 3 extra states for the offer types instead of just the one for the drink. This makes sense to me but will imply more changes in the UI.
