### ISSUE TITLE
Archetype oasp4j-template-server contains restaurant-related code

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [oasp/oasp4j#175]
when I create an 'empty' OASP4J project using new Maven Project (from Archetype oasp-template-server) I find some restaurant code in it, see e.g. PermissionConstants, Role, NlsBundleRoot.errorOfferEmpty. I guess this has to be cleaned from the archetype.

**Comment by hohwille** [comment]
The PermissionConstants are correct but maybe not the content in there. This is already known and was discussed in #15 due to a bug in the currently simple mechanism to mark code-lines from our sample to be excluded in the template.
We also have Role there and some of the initial stuff to allow that a login is already possible.
In general you are right and we need to improve here.
There is also #171 that has been fixed but in the current released archetype is still wrong.
I think it is still a good starting point but as you can imagine it is still a first 1.0.0 release and will improve over time...

**Comment by hohwille** [comment]
As @Jan-PeterRichterCG described in #176 also Money and related classes are part of the archetype. These shall be excluded as well.

**Comment by hohwille** [comment]
@julianmetzler excellent :+1: 
Can someone test the latest archetype and verify that we can close this issue now?

**Comment by julianmetzler** [comment]
The Java part seems to be ok now, in xml resources are still some application specific snippets (e.g. *access-control-schema.xml*).

**Comment by julianmetzler** [comment]
related commit: https://github.com/oasp/oasp4j/commit/8c3dd2311e857a346974722a92bf984873b48509

This should be fixed now.

**Comment by hohwille** [comment]
Thanks. Seems complete now.
