### ISSUE TITLE
Archetype oasp-template-server apparently contains classes that should be placed in a library

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [oasp/oasp4j#176]
when I create an 'empty' OASP4J project using new Maven Project (from Archetype oasp-template-server) I find lots of classes that I would have expected to be part of a library, e.g. all the Money-related ones but also most of the other classes that I find in my 'empty' project. Does OASP expect a *user* of OASP to augment these classes in one or the other usage scenario [where just subclassing is not possible for whatever technical reason]? When I look at NamedQueries it is obvious that this is just an empty shell where I put my named queries in ==> OK! But what about AbstractBeanMapperSupport? What is the usage scenario where I have to *change* that code?
(I have to admit that I have not read the architectural documentation yet :-) )

**Comment by hohwille** [comment]
This is absolutely intended! We mainly want to provide patterns rather than a framework (https://github.com/oasp/oasp4j/wiki/architecture#key-principles). It is therefore better to give this code away as part of the template and allow users to change and evolve the code as they need rather than creating yet another framework that projects have to fight with or against.

**Comment by hohwille** [comment]
> all the Money-related ones

shall be handled with #175
