### ISSUE TITLE
Memory issue on Jenkins

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#195]
I currently observe random memory issues in the nightly builds.
You could find the following messages in the failed builds. Is there a chance to upgrade memory on the build machine?

```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 116391936 bytes for committing reserved memory.
```

**Comment by sobkowiak** [comment]
This was already observerd here #124. It is probably caused by the cargo & tomcat way of itests. The test Tomcat instance is sometimes still running after the build is finished. I think not all is correctly shut down and the memory is not correctly cleaned-up by the itests.  It should probably be fixed when we migrate the tests to arquillian (#124)

**Comment by may-bee** [comment]
Arquillian is not yet fixed as far as I know, but obviously it makes sense to wait for this decision. If arquillian makes a good job, it is worth checking whether the problem will vanish automatically.

**Comment by sobkowiak** [comment]
We can restart Tomcat 2-3 times a week. It should help for now.

**Comment by hohwille** [comment]
with the simple maven/cargo approach we have a lot of trouble. If we can switch to Arquillian and this will work reliable, this will be an argument for itself so IMHO then we have nothing more to discuss about the change. We should get some activity on an Arquillian I-Test prototype and then see how it works.

**Comment by MarcoRose** [comment]
https://github.com/devonfw/devon-ci/issues/1
