### ISSUE TITLE
Deployment for Standalone Tomcat on Ubuntu

### ISSUE THREAD

**Issue by tonqa** [oasp/oasp4j#210]
I am trying to do a deployment for a Tomcat on Ubuntu. However, the WAR from the build process seems to be misconfigured. The Tomcat on Ubuntu does not start the application correctly and does not produce any application-specific logging information as well.

Currently I build the WAR file on Windows by executing the steps below. Then I find the WAR file below _oasp4j\oasp4j-samples\oasp4j-sample-server\target_. 

    mvn clean install -f oasp4js\java\pom.xml
    mvn clean install -f oasp4j\pom.xml -Pjsclient

The resulting WAR file works on Windows but not on Ubuntu. Am I missing something?

**Comment by hohwille** [comment]
@tonqa your build instructions seem correct.
Can you look at ``` logs/catalina.out``` and see if there is something pointing out to the actual problem?
I tried the same on Ubuntu-Server 14.04.1 LTS _Trusty Tahr_ and it works without problems.

**Comment by tonqa** [comment]
@hohwille Die catalina.out wurde bei mir auf dem Ubuntu-Server nicht erstellt. Es hat sich außerdem herausgestellt, dass die H2 Datenbank bei mir falsch aufgesetzt wurde. Ich bekomme jetzt immer ein H2-spezifischen Fehler, den ich noch nicht beheben konnte:

    Caused by: org.h2.jdbc.JdbcSQLException: Verbindung ist unterbrochen: "unexpected status 16777216"
    Connection is broken: "unexpected status 16777216" [90067-176]

Könnt Ihr das Setup und die Konfiguration einer H2 Datenbank mit in den Data Access Guide mit aufnehmen? Das würde die Arbeit beim ersten Deployment der WAR und der Verbindung zur Datenbank für alle gut dokumentieren und extrem vereinfachen.

**Comment by tonqa** [comment]
Related to issue #76 (Documentation for Deployment)

**Comment by hohwille** [comment]
Actually we are using H2 and flyway because it needs no setup and works smooth. Sorry if you are facing errors.
For flyway see here in our docs:
https://github.com/oasp/oasp4j/wiki/guide-database-migration
For our H2 config have a look here:
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/resources/config/app/dataaccess/beans-db-server.xml
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/resources/config/app/dataaccess/beans-db-plain.xml
So you also trigger the spring profile ```db-plain```
The port comes from here:
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/pom.xml#L19

and is 8143 by default as you can see. Maybe that conflicts with something on your machine. Either use ```db-plain``` or change the port (```database.h2.server.port```).

**Comment by tonqa** [comment]
@hohwille Thanks for your help, to fix the error case I had to reinstall the proper version of the manually installed H2 database from 1.4.x back to 1.3.176. So the application does start up properly.

However I have still got left the problem that I get no application specific logs on Ubuntu. I tried to use lsof to find out if the tomcat has any other log files open, but it does not. Do I have to put the logback.xml somewhere and change the log level or what do you suggest?

**Comment by hohwille** [comment]
I can not access your machine to see what might be miss-configured. However, in my case a vanilla WAR of oasp4j-sample-server works fine in my tomcat and logs fine. The only issue I just realized is that the filenames contain extra dots: ```localhost_access_log..2015-03-11.txt```.

Where did you build the WAR from? Can you provide the git revision hash? Did you use master or develop branch? Maybe just extract the WAR and have a look at the contained logback.xml. To tweak just place your own copy in tomcat/lib folder.

Can we close this issue? (we will still improve docs due to existing tickets and I will create one for the extra dot```)

**Comment by tonqa** [comment]
I used the develop branch with OASP version 1.1.0. I built the WAR on a Windows computer. I find the logs on the Tomcat on Windows but not on the Tomcat on Ubuntu.

And what do you think why the test data could not have been imported?

**Comment by amarinso** [comment]
I've found that the location of the files is dependent of the CWD where you start tomcat. If started by:

tomcat$ ./bin/startup.sh

then the logs are located on a folder at the same level than tomcat. 

only if started from inside the bin directory the logs are located inside tomcat/log where they are meant to be and where the comment on the logbak.xml points to.

By the way, on this issue I've found the undocumented -Pjsclient to build the WAR file with the included client files. I think this should be promoted on the documentation because we where missing exactly this functionality (!)

**Comment by hohwille** [comment]
@amarinso thanks for that info. I thought the logdir was relative to CATALINA_BASE and not to PWD of the start script. That actually sucks. We need to find a better solution. I just created #213 for that bug.

Feel free to add the -Pjsclient feature to the documentation but it will be gone with the next release anyway as we will use git modules instead to link server and client and have no need anymore for such a weak bridge then.

**Comment by amarinso** [comment]
@tonqa do you think this issue can be close? did you have any other problem?

**Comment by tonqa** [comment]
Thanks, the deployment worked with the hints you provided above.
