### ISSUE TITLE
Simplify REST-usage at service layer

### ISSUE THREAD

**Issue by MarcoRose** [oasp/oasp4j#221]
Based on the discussion in yammer the REST usage in OASP4j is to be simplified.
HTTP-GET for single entity-get (optional for lists)
HTTP-DEL for single entity-delete (optional for lists)
HTTP-POST for all other usages like business use-case calls, write, replace, search with parameters
HTTP-PUT: not suggested

Example, Doc and Generator to be amended.
This proposal needs to be confirmed by the lead-architects.

**Comment by hohwille** [comment]
This would be totally fine for me and makes sense.
Maybe we would also find a generic addition later some time that would automatically transform GET requests with query parameters on collection URL to the according logic behind the according POST for the search by criteria, but this is just a nice to have and fully optional.

**Comment by henning-cg** [comment]
As posted by @MarcoRose, the proposal is to optionally allow GET for list loading, but to use POST for searching.

I would opt to see pagination as a sub-case of searching, and therefore to use also use POST for sending pagination parameters.

This would also be important to know in order to define the metadata protocol.

Any comments on this?

**Comment by MarcoRose** [comment]
Yes, my understanding too, pagination is a cas of searching -> Use POST

**Comment by amarinso** [comment]
Playing devil's advocate here I think a query to a resource with pagination could be valid for GET because all we are asking for is a projection of the compound "entity collection".

It is also true that for entities with more than a few results you always combine pagination with some kind of filtering.. and that way the GET query string becomes less useful for manually using it on development (one of the advantages of using GET)

I would like to hear other opinions from the proponents of keeping GET.

I think we should easy the URI parameter transformation on the REST controllers with a helper method and allow GET for this use case.

**Comment by hohwille** [comment]
@amarinso I think we already agreed to remove GET for queries. My suggestion was only if an easy generic and optional addon could be done, this will be helpful. We can move that out of the sample and the "Standard" entirely. No problem for me.

**Comment by amarinso** [comment]
Sorry @hohwille I dindn't concluded that we were removing GET for all querys, but only for "more complicated" ones.

So, just to be sure, are you saing that we should change for example this from the sample app:

````java
  @Path("/order")
  @GET
  public List<OrderCto> findOrders(@Context UriInfo info) {

    RequestParameters parameters = RequestParameters.fromQuery(info);
    OrderSearchCriteriaTo criteria = new OrderSearchCriteriaTo();
    criteria.setTableId(parameters.get("tableId", Long.class, false));
    criteria.setState(parameters.get("state", OrderState.class, false));
    return this.salesManagement.findOrderCtos(criteria);
  }
````

to this format?

````java
 @Path("/order")
 @POST
 public List<OrderCto> findOrders(OrderSearchCriteriaTo criteria) {
    return this.salesManagement.findOrderCtos(criteria);
 }
````

**Comment by hohwille** [comment]
jep. exactly. However, your initial suggestion was to add some more segment to the path after the collection URL. Regular POSTs on the collection URL are typically a save operation. IMHO we should therefore separate this by URL and not only polymorphic. But everything else is perfect KISS.
WDYT?

**Comment by amarinso** [comment]
So... how do you suggest to do it in this example, maybe this?

````java
@Path("/orderfind")
@POST
public List<OrderCto> findOrders(OrderSearchCriteriaTo criteria) {
    return this.salesManagement.findOrderCtos(criteria);
 }
````

I still prefer something like
```java
@Path("/order/find")
```

so you can have also things like

````java
@Path("/order/findAdvanced")
````

By the way, in order to add more "noise" to the conversation I've remembered something about GET vs POST that could be taken into consideration for extreme performance cases:

> Use GET for AJAX Requests
>
>POST is implemented in the browsers as a two-step process: sending the headers first, then sending data. So it's best to use GET, which only takes one TCP packet to send (unless you have a lot of cookies)
> - https://developer.yahoo.com/performance/rules.html


Also a case against GET with complex parameters is that as they are part of the URL they get logged as the go through intermediate proxys or front-end servers which can be bad from a security point of view or because logs grow because of the data.

**Comment by tbialecki** [comment]
First of all why are we not using resource oriented
urls(@Path("/order/findAdvanced"))?
GET /order
POST /order
DELETE /order


Secondly there is new trend(achritecture) called HATEOAS - contraint for
REST architecture.
https://spring.io/understanding/HATEOAS
Was it discussed ?

According to HTTP specification, POST is considered as request triggering
an action on server(which can change state of server).
Search requests are for sure not that ones.

2015-05-23 0:19 GMT+02:00 amarinso <notifications@github.com>:

**Comment by amarinso** [comment]
I've yet to see the advantage of a HATEOAS approach. I can not think how any of the systems I've built or know about, could have taken advantage of this. It's nice from a theoretical point of view thou.

But to have a productive framework I think we have to take a more practical approach.

Resource oriented urls in my opinion are fine when doing CRUDs but there are more corner cases than those alone.

When using complex parameters on a GET request it gets messy both on the client, the url and the server. It's easier to go POST and embed the complex object as json on the payload.

There could be an alternative route of using GET with a complex object by serializing the data on a query parameter, like this

```
http://some.test/aresource?query={"paramA":"value1", "paramB":"value2"}
```
and then having a mechanism on the server that does the work to convert it back to a DTO. I'm unaware of that functionality already supported by the standard.

**Comment by amarinso** [comment]
It seems there is an CXF extension that can be used for "advanced search querys" with nested beans support on the query params

http://cxf.apache.org/docs/jax-rs-basics.html#JAX-RSBasics-Parameterbeans

but again, not inside the standard :-(

**Comment by hohwille** [comment]
We had various discussions about HATEOAS and decided against it. It is making something simple (REST) to something rather complex causing effort - so IMHO more like these overcomplicated WS-* stuff that finally killed SOAP. HATEOAS can make sense if you want to consider the entire world as your service-users. But we are not google or facebook and so it is not worth the extra effort and overhead.

**Comment by hohwille** [comment]
We had a lot of discussions about GET vs. POST for criteria queries also.
An important argument from @amarinso that I agree on is development effort. Also security, logs, URL-Size-limits, mapping complex data-structure to get parameters, etc.
We decided that if we want to send actual objects from the client to the server that we want to use JSON and that means we do a POST (and we agreed on ignoring PUT as alternative).
So for me this is fine:

    @Path("/order/find")

If we can offer a generic optional add-on that will automatically take a GET on /<entity> map the query parameters to JSON and delegate that to POST on /<entity>/find this will be welcome so we have the best of both worlds without extra effort for those who like it.

**Comment by hohwille** [comment]
Can someone summarize what is left to do here? I think we can close this. Maybe check if documentation is up-to-date...

**Comment by lgoerlach** [comment]
Yes, I don't see anything left to do except for documentation. I will update it [here](https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-service-layer#rest) and then we can close it IMHO.

**Comment by amarinso** [comment]
@lgoerlach I've already added something to the guide [here](https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-service-layer#recommendations-for-rest-requests-and-responses)

**Comment by lgoerlach** [comment]
> @lgoerlach I've already added something to the guide here

Ok, looks great :+1: There is everything you need to define the REST services.

But should we really keep the paragraph I linked above? It seems to be "legacy" documentation which is older than this issue here.
I find it a bit confusing if we first paraphrase the wikipedia article on REST there and later we say "REST is great, but we do it differently in this case. And this case. And that case.".
It might be a more complete approach but if I would read the page for the first time and tried to understand everything in Table 2 (e.g. PUT) just to be told "forget PUT" a few paragraphs later, it would feel like wasted time.
It's still correct and logical but burdens the reader with information which he can ignore later on. If the guide's focus lies on enabling the user to use our best practices rather than explaining everything related to them, we should abridge it at least. But maybe that's just my opinion - and sorry for the long comment :-)

**Comment by amarinso** [comment]
I fully agree with @lgoerlach . I've reworked a bit the [rest chapter](https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-service-layer#rest), can you take a look at it?

I've tried to keep everything, maybe it's better to simplify

**Comment by lgoerlach** [comment]
@amarinso Thank you, that's perfect to me.

We don't have to remove the canonical REST as long as it becomes clear to the reader that it is just there for further information and not relevant for implementing OASP web services.

**Comment by amarinso** [comment]
Ok, let's close this issue then :)
