### ISSUE TITLE
Adjust CORS server configuration

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#223]
Developing an oasp4mobile approach, we currently facing problems with the cross-origin-policy.
This issue should collect all ongoing work on this.

Afterwards, we may want to have a security audit on the final configuration.

**Comment by dsanche2** [comment]
Are you still working in this issue?

We need CORS support also when working with Sencha Cmd tools because they serve files from a local server different from tomcat.

We've found that the current implementation was lacking a bit of functionality for our case:
- Add correlationId, X-CSRF-TOKEN and Cookie as default allow-headers in the response.
- Add Access-Control-Allow-Credentials header in the response.
- Return value of origin header in the response header Access-Control-Allow-Origin. In AJAX request we have to activate flag withCredentials to allow Cookies and you can use "*" value in the Access-Control-Allow-Origin response header.
- Modify the filter chain to accept OPTIONS http without requiring authentication (when doing CORS from browser makes a "pre-flight" request to the server with OPTIONS in order to verify that the real request can be send).

If you are not working in that we can continue with this issue.

**Comment by may-bee** [comment]
For devonfw/draft-tukl-oasp4mobile we found a client-side solution to cope with CORS.
Thus we removed the latest configuration from the server again (see last commit).

The problem we were facing with the CORS implementation was, that by allowing all origins

```xml
<init-param>
      <param-name>cors.allowed.origins</param-name>
      <param-value>*</param-value>
</init-param>
```

You cannot login any longer properly as cookies will be disallowed in combination with CORS by default. But meanwhile I have found that there might be some path to workaround this defaults: http://blog.dzhuvinov.com/?p=1015

For now I am out here, but I will observe the progress and we will see whether your solution also works in the mobile project. :)

**Comment by dsanche2** [comment]
Yes, we have already dealed with that. In our Sencha client we send all request with withCredentials flag to true and in server side, we don´t accept origin from `"*"` we accept origin from the url that sends the request (because withCredentials flag to true you can not put "*" as allowed origins.

I´m going to document this issue in Devon wiki and I will put the link here so you can check it if you want

**Comment by may-bee** [comment]
:+1: great. Thanks!
I am looking forward to test your solution with our mobile clients.

**Comment by dsanche2** [comment]
I have created a new branch `cors-support`in my OASP fork. This branch contains:

* CORS filter class.

* CORS filter bean definition in `beans-security-filters.xml` and CORS filter added to Spring chain filter in `beans-security.xml.`

* Default propertie value to enable/disable CORS filter.

This configure server side to support CORS, but, as you know, you still need configure client side. You have to add `withCredentials` propertie in your request and it should be work.

You are free to check it and give me your feedback and if you consider it good to include it in OASP, I will do a PR.

**Comment by amarinso** [comment]
Move the functionality currently on IP for the CORS support to Open Source sample application

**Comment by may-bee** [comment]
see #274
