### ISSUE TITLE
Change Logger initialization to use container injection

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#252]
We are recommending injection pattern of services on our classes but when logging we are obtaining the instance through `LoggerFactory.getLogger`.

example:

```java
  private static final Logger LOG = LoggerFactory.getLogger(UcFindTableImpl.class);
```

We could simply use `@Inject` and avoid also the `static` variable for the class and possible copy&paste errors because the logger qualifier is assigned from the producer method.

```java
@Inject Logger LOG;
```

We are using this technique on Java EE 6 and works fine, it's a matter of finding a proper way to do it with Spring. There is already some samples on how to do it as well as some corner cases:

http://rbergerpa.blogspot.com.es/2011/02/dependency-injection-and-logging.html
http://stackoverflow.com/questions/6351082/using-java-annotation-to-inject-logger-dependency
http://java.dzone.com/articles/injecting-loggers-using-spring

**Comment by hohwille** [comment]
I used to do that, too (and created a base-class that other components/spring-beans can derrive from and simply call ```getLogger()```). However, I was convinced by others to use the RF pattern that we suggest for OASP.
After all this is again a philosophic discussion that is leading nowhere. You have to make one decision and stick to it. If you are using SLF4J you win nothing by making that injected. Eclipse is smart enough to replace the qualifier on copy&paste of classes.
Further people one the web are arguing that the non-static variant is wrong because then a super-class loggs to the same logger as the sub-class. Hence if you extend a spring-bean and replace the original one then your log-statements will go to a different logger afterwards.Others argue in the opposite direction that the same instance is logging to different loggers.
This is just religion and there is no _truth_.
I personally do not care. I just want to have a decision and stick to it. Try to convince all the others if you think that there is something to win here.

**Comment by amarinso** [comment]
Well, what I want is to have arguments in favour or against our decisions.

I see more coherent to use injection as we recommend this pattern along the application.

If the log has to be associated to the class holding the original property it can also be done with reflection on the producer class. Or make it optional with custom annotation.

But I recon that this is not a very widely spread pattern and even Spring is using the `LogFactory.getLog` method.

For me I will go with the change... and even change the LOG variable name to lowercase since it is quite disturbing.

Please "others" :-) provide more arguments for not switching

**Comment by hohwille** [comment]
http://stackoverflow.com/questions/6653520/why-do-we-declare-loggers-static-final

**Comment by hohwille** [comment]
http://www.slf4j.org/faq.html#declared_static

**Comment by hohwille** [comment]
While apache software foundation suggest the same as @amarinso 
http://wiki.apache.org/commons/Logging/StaticLog

**Comment by maihacke** [comment]
How do we initialize the logger in non spring-beans then?

**Comment by hohwille** [comment]
To extend the question of @maihacke 
What will you do if you want to log from a static method (e.g. if you provide a Util)?
In my mmm project I was fighting statics and created Interface+Implementation even for Utils and initialize them as spring beans as well. However, this is making things more complicated.
The current approach is simple and works for every case.

**Comment by amarinso** [comment]
I think that if this is what we recommend (utility classes with static methods) we should add it also on the platform guide.

But then we are going against our recommendation of using IoC.

Whenever I've used static classes for easing development I ended also doing horrible things to inject services on some of this classes (like creating setters beans of type `org.springframework.beans.factory.config.MethodInvokingFactoryBean`)

But if we aim to do it "properly" we should follow the mmm project on this (and also document) and avoid static whenever it is possible.

@hohwille maybe is an option for utility classes to just declare the implementation and not the interface? (talkint to @nelooo he pointed out that using implementation without interface will revert Spring to use cglib instead of Java proxies which brings sometimes problems)

If we where to use Java8, we could think of using interfaces with default methods and having a BeanFactory to automatically create the beans... but maybe it is too much magic involved

**Comment by hohwille** [comment]
We are loosing track here that was initially about logger style. However...

> Whenever I've used static classes for easing development I ended also doing horrible things to inject services on some of this classes

This is always the story about design. You need to clearly distinguish between stuff like a StringUtil that works with just static methods and no IoC and logic that should be modular and extendable. The recommended approach is to create a IoC/CDI-bean (aka "spring-bean"). But in case of a StringUtil this is really overkill to create interface, impl and @Inject it whereever it is needed especially requiring a setter for injection to follow our guidelines. Come on. Even if you would omit the interface this is a pointless burden for developers. You can do it if you want to avoid static (except for constants with final) and create perfect, extend-able code but nobody should be forced to do so as this would be ridiculous for many users. So IMHO we need to accept that people will create Utils with static methods for simple things and I am fine with that.

If we accept that and such Utils require a logger we need the static logger pattern. If again we accept the static logger pattern for that purpose we should better accept it in general rather than mixing different styles of logger patterns.

The alternative would be to recommend clean IoC and logger injection and stick to that in our sample. In reality we would leave people alone to decide about Utils and static logger access what will in the end lead to a mixed logger pattern.

**Comment by amarinso** [comment]
> In reality we would leave people alone to decide about ...

Well, if we want to provide added value with things like sonar rules that check for valid/invalid use of statics, or a generator for classes,  we should clearly decide and not let everyone choose their weapon.

That said, we can leave this as it is today and I will add to the documentation the decision.

- The exception for the logger to the rule of injection
- The accepted use of static classes for pure static methods

**Comment by amarinso** [comment]
It is still open the question to change the case for the variable to be `log` instead of `LOG`. 

I've checked both SpringFramework and logback projects and they are using lowercase for `static final Logger` instances.

**Comment by hohwille** [comment]
> It is still open the question to change the case for the variable to be log instead of LOG. 

We follow Oracle Code conventions. Constants are UPPER case.

**Comment by amarinso** [comment]
Ok, I've seen the reference to the Oracle Code conventions and is a bit ambiguous (it also says that is non further under revision since 1999!)

We also reference Google Java Style on the OASP platform guide where we find this as examples of what is constant and what is not:

```
// Constants
static final int NUMBER = 5;
static final ImmutableList<String> NAMES = ImmutableList.of("Ed", "Ann");
static final Joiner COMMA_JOINER = Joiner.on(',');  // because Joiner is immutable
static final SomeMutableType[] EMPTY_ARRAY = {};
enum SomeEnum { ENUM_CONSTANT }

// Not constants
static String nonFinal = "non-final";
final String nonStatic = "non-static";
static final Set<String> mutableCollection = new HashSet<String>();
static final ImmutableSet<SomeMutableType> mutableElements = ImmutableSet.of(mutable);
static final Logger logger = Logger.getLogger(MyClass.getName());
static final String[] nonEmptyArray = {"these", "can", "change"};
```

Please note the explicit example about the logger...

**Comment by hohwille** [comment]
OK. If that is of any help, lets change the code and the eclipse template configuration then.
I do not care...

**Comment by hohwille** [comment]
Checkstyle can not make this distinction. Do you want to propose fixes for checkstyle, sonarqube, etc.?
Come on lets just keep it as is.

**Comment by hohwille** [comment]
IMHO we should update the documentation as suggested and then close this as ```wontfix```.

**Comment by hohwille** [comment]
I've just seen that you already comitted the changes (not associated with this issue, so I did not see that before). Shall we revert then?

**Comment by amarinso** [comment]
Oh oh... I didn't intended to comit the changes... I wanted to create a pull request instead for someone else to approve

my fault, I don't know how I've done done it.

How do we proceed to revert it?

**Comment by amarinso** [comment]
Oooops... I see what has happened.

I made 2 PR this morning, one for fixing the integration test and after that, one for the refactoring of the LOG variable.

This seems not to be good because the second commit went on your approval of the integration test fix!

Now working with @henning-cg to try to revert this last commit

**Comment by amarinso** [comment]
Ok, commit reverted. Let's close this.

**Comment by hohwille** [comment]
no problem. Thanks. BTW: SonarQube supports your suggested style but checkstyle still does not. As Checkstyle is still widely used and the best way to get early feedback in Eclipse I think reverting was best choice. Let us better concentrate on simplifying component facade / UC stuff.
