### ISSUE TITLE
Add pagination support for entities other than Table and Offer

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#261]
Continuing issue #193 we start another issue to add pagination to following entities:

- Offers

do we require others?

**Comment by lgoerlach** [comment]
I checked the REST services that are currently implemented and the use case overview for the example application.
We could also add pagination to:
* StaffMember entities and
* Product entities

because both shall get a CRUD interface for the chief in the future.

Any objections? Otherwise, I could start implementing the changes.

**Comment by hohwille** [comment]
Fine. Go. In the end we should have no REST service returning a plain List (e.g. ```List<MyEto>```).

**Comment by amarinso** [comment]
Mmmm... and what about master data entities? shouldn't be allowed to return List<MyEto> ? For example for combos or lists... should always be pagination involved but with a very high limit?

**Comment by hohwille** [comment]
IMHO limit can still be switched off. However @henning-cg explained that using List is a security pitfall causing JSON vulnerability in the client that we need to avoid.

**Comment by hohwille** [comment]
Done. Thanks @lgoerlach :+1:
