### ISSUE TITLE
Improve server business error messages

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#340]
The server often does not provide helpful error messages. e.g.:

if I try to delete a product which is still part of an offer then I get:

``` json
{
 "message":"An unexpected error has occurred! We apologize any inconvenience. Please try again later.",
 "uuid":"e143897b-54b1-481e-8d25-c270a9089bf7",
 "code":"TechnicalError"}
```

Positive example, if you try to create an empty offer:

``` json
{
 "message":"The offer is empty - it must contain a drink, meal, or side-dish!",
 "uuid":"0f8d0d42-5efa-4e26-8e66-c4d9ffc128d9",
 "code":"OfferEmptyException"}
```

**Comment by sesslinger** [comment]
Those generic, not helpful messages are due to missing custom exception handling in some cases. 
In the given example, there is no check whether the entity to delete is referenced by another entity.
So we should catch that kind of exception in `io.oasp.module.jpa.dataaccess.base.AbstractGenericDao<ID, E>.delete(ID id)` and provide some useful information in `io.oasp.gastronomy.restaurant.general.common.api.NlsBundleApplicationRoot'`.

As you mentioned, those not helpful server messages occur often. So in general  it might be useful, if we identify similiar scenarios, which also could benefit from custom exceptions/messages.

**Comment by hohwille** [comment]
There is also another reason for this: Technical exceptions are shadowed on security purpose so you only see this generic error message. We can think about a development option to disable the feature but it should be enabled by default and always in production. See:
https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure

**Comment by hohwille** [comment]
The one thing is to add user-exceptions for arbitrary end-user error situations. However, this is what is typically addressed by validation in the client. Validation on the server for such cases is only for security and robustness. Hence, a nice error handling for that is this way a nice-to-have. Be aware that due to the technology gap between client and server this causes code duplication and extra effort. Such cases can be handled much nicer with cross-compiling approaches such as GWT or exivalents for mobile (that cross-compile your java code to native mobile code). In such a scenario you can share code between server and client as everything is just pure Java.

**Comment by may-bee** [comment]
Yes, there are also security concerns. Nevertheless, we should then discuss which error messages are worth to be shadowed. I do not think, that the first example in the opening post is of any security concern if the server answers with a appropriate error message.
Shadowing any exceptions, it can also get quite complex to analyze errors occurred in productive environments.

**Comment by hohwille** [comment]
> Shadowing any exceptions, it can also get quite complex to analyze errors occurred in productive environments.

Did you read the exception and logging concept (UUIDs, etc.)?

**Comment by may-bee** [comment]
Yes, you are right. But you might not always be in the good position to be in control of the server or any other external system your system under development should be communicate with. In this case you will higher the development efforts tremendously. You will have to get in touch  with the other systems administrators quite fast if your messages are not accepted by the external just returning a non-sounding general error message.

I am with you regarding security to shadow as much technical information as possible at the outer system boundaries. Nevertheless, it might be interesting to be discussed where to draw the line.

**Comment by hohwille** [comment]
If you follow the standards for validation IMHO everything works as expected. If you implement custom exceptions like `OfferEmptyException` you need to read the according guide (https://github.com/oasp/oasp4j/wiki/guide-exceptions). However, I do not recommend to write such custom exceptions for very business specific validation scenarios.
Can we close this issue?
Otherwise could you please make clear what you suggest to change?

**Comment by maybeec** [comment]
Ok. Agreed.
I think in this sample application we should put it as ideal as possible to the guidelines. You most probably will have some exceptions here in real world examples depending on the accessibility of logs of the backend systems.
