### ISSUE TITLE
Exception in ToggleFilterWrapper (misses a setter for disabledString)

### ISSUE THREAD

**Issue by ivanderk** [oasp/oasp4j#349]
Running an application -created with the 1.3.0 template- with current HEAD (develop) of the github repository results in an exception at server start-up

Cause of the exception is that io.oasp.module.web.common.base.ToggleFilterWrapper  misses a setter for disabledString.

Is this a bug or a compatibility issue between 1.3.0 and current development branch?

**Comment by amarinso** [comment]
I think ToggleFilterWrapper now works with positive logic, so the setter is for the "enabled" field, and not "disabled".

**Comment by ivanderk** [comment]
Correct. I missed that one. Thanks!

**Comment by hohwille** [comment]
That was introduced in PR #350.
I actually did not get why the logic had to be inverted and this turns out as a compatibility problem.
IMHO this still still a bug in sample and app-template that also has to be fixed.
If you create a new project based on archetype and that fails to startup then we have a bug!

**Comment by amarinso** [comment]
I think that the logic to have things enabled/disabled is easier if we have:

`some.filter.enabled=true`

than if we have to write

`some.filter.disabled=false`


In order to test the archetype automatically I think we could create a job on jenkins for this. Create an app, deploy to a test server and test it runs ok. Do we create an issue for this?

**Comment by hohwille** [comment]
IMHO boolean values should be designed in a way that false is the reasonable default.

**Comment by hohwille** [comment]
Further it was designed as system property on purpose. If that property is added to application.properties then it will be comitted accidentally. As a system property everybody is free to change his personal launch config.
