### ISSUE TITLE
Security leak in the sample in current release

### ISSUE THREAD

**Issue by sroeger** [oasp/oasp4j#456]
This is connected to #424.
Actually the overwritten additionalAuthenticationChecks in https://github.com/oasp/oasp4j/blob/develop/samples/core/src/main/java/io/oasp/gastronomy/restaurant/general/common/impl/security/ApplicationAuthenticationProvider.java#L47 opens the doors for intruders in the sense that there is no password check anymore. You can simply login with waiter/chief or whatever and leave the password blank or enter anything.

Out commenting that method override in ApplicationAuthenticationProvider restores the password check but does not really log the user in as it does not grant access.

**Comment by hohwille** [comment]
This is actually a very critical bug that should be fixed asap.
The crazy thing is that our implementation of springs AuthenticationProvider API throws an BadCredentialsException in additionalAuthenticationChecks, but Spring catches this error and then still handles the login as success due to some other default AuthenticationProvider returns a result and then spring finally ignores the catched exception.
This IMHO is also a severe spring bug...
However we need to do our own homework first and fix our bugs.

**Comment by hohwille** [comment]
fixed.
