### ISSUE TITLE
upgrade to flyway 5

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#459]
We should update to flyway 4.x asap. The migration from 3.x to 4.x can cause pain as checksums are recalculated and therefore ignored on this step what is a very "brave" approach of flyway.
In flyway 3.x there are bugs such as that can cause unnecessary pain:
https://github.com/flyway/flyway/issues/253

**Comment by GawandeKunal** [comment]
Hi All, 

For Flyway Migration from 3.2.1 to 4.0.2 , following is the solution approach that we have come up with : 

1) 	Added new dependency for flyway 4.0.2 (stable released version as mentioned on flyway site https://flywaydb.org/blog/flyway-4.0.2.html ) in pom.xml of oasp4j-bom (which is recommended always ).
2)	  Added the following 
      <dependency>
        <groupId>io.oasp.java</groupId>
        <artifactId>oasp4j-bom</artifactId>
        <version>${oasp4j.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

in pom.xml of oasp4j-samples before the existing entry 

 
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
         <type>pom</type>
         <scope>import</scope>
      </dependency>

under  <dependencyManagement> tag.

3) 	With these changes , we are able to compile oasp4j project (mvn clean install -DskipTests=true). 
4)	 But when we do complete install (mvn clean install) Junits are failing . 
   We are currently debugging Junit failures . Let us know if the solution mentioned above  looks fine ?

Thanks ,
Kunal Gawande

**Comment by ivanderk** [comment]
@jomora  would you be so kind as to help out with this issue?

**Comment by GawandeKunal** [comment]
Hi All,

Just to add , in  the solution mentioned above, we have added dependency for oasp4j-bom in pom.xml of oasp4j-samples before springboot dependency  since adding springboot before oasp4j-bom dependency ,  flyway 3.2.1 that was part of springboot was picked. After adding as mentioned in above solution , flyway 4.0.2 is picked. 

Thanks.
Kunal Gawande

**Comment by jomora** [comment]
I investigated the issue and came to the following conclusion which definitely **must be discussed** by the architects before the solution is implemented.

Investigation:
I applied the changes proposed by @GawandeKunal and I was able to reproduce the change of flyway-core version. Thanks for the explanation! :)

Then I read up Maven's [dependency mechanism](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html). One section includes some examples and is dedicated to  BOMs (search for 'bom' on the website).
There, the following project structure is suggested for usage of BOMs:
![working_example](https://cloud.githubusercontent.com/assets/5971366/17962009/01d3072c-6aaf-11e6-844b-9ff9cc2a439e.png)
(Black arrows: parent-child relationship, white arrow: import via dependencyManagement)


Then I checked the project structure of OASP4J and found the following:
![defunct_structure_2](https://cloud.githubusercontent.com/assets/5971366/17962164/d883e106-6aaf-11e6-802f-6cc7adb8cc6a.png)

Take a moment to understand the difference: in the first picture the BOM project is the parent project, but in the OASP the BOM project is a subproject. I was able show that the problems with the flyway dependencies are caused by this project structure.


My conclusion:

To make the OASP4J BOM work the BOM must become the parent project of the main OASP4J project as depicted in the following graph:
![working_structure](https://cloud.githubusercontent.com/assets/5971366/17962281/55819dba-6ab0-11e6-936d-830d1c1b7514.png)

This solution has one issue. Since `oasp4j-samples` is a subproject of the main OASP4J project, the BOM would also be inherited and, hence, the BOM is not needed in the `dependencyManagement` section of `oasp4j-samples`. Now, since the samples are developed to show how to use the OASP4J in real world projects, the dependencies should be implemented accordingly.
Therefore, the main OASP4J parent project should **not** be the parent of the samples. The samples should only import the framework via the dependency mechanism - not via a parent-child relationship.

The following graph should clarify the structure I propose:
![working_structure_unrelated](https://cloud.githubusercontent.com/assets/5971366/17962504/8487c804-6ab1-11e6-839e-5c9b31bcc42a.png)


However, these changes will have a deep impact on the OASP4J and, therefore, must be discussed thoroughly by the architects.

What do you think @maybeec, @ivanderk, @hohwille, @maihacke , and whoever I forgot to mention?

**Comment by GawandeKunal** [comment]
Hi All, 

With the solution that I have mentioned earlier [Please refer my first post for the solution], We are facing errors in two Junits (ProductImportJobTest & BillExportJobTest). when we do "mvn clean install".

Error is 
'org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 0001' . Please refer [junit_logs.txt](https://github.com/oasp/oasp4j/files/444425/junit_logs.txt)  for detailed error logs. 



This seems to be an existing issue with flyway 4.x [https://github.com/flyway/flyway/issues/988] and this issue is still open with flyway.

**Comment by ivanderk** [comment]
However, in the issue they make a reference to https://github.com/flyway/flyway/issues/989
which *is* marked as closed at it pertains to fix https://github.com/flyway/flyway/commit/846233f86b98be034dfe5b690ef566a531ea55a2

Did you try that?

**Comment by kiran-vadla** [comment]
@ivanderk ,

Sincere Apologies . Existing issue with flyway 4.x that was mentioned in the above comment was incorrect . It is [ https://github.com/flyway/flyway/issues/1352 ]

Thanks
Kiran.

**Comment by hohwille** [comment]
I am slightly confused with the flyway error 1352 as we are using flyway 4 in my project and do not face that problem. Howerver, if that is the case we should postpone the update to 4.x until 4.1. is released and the bug is fixed.

**Comment by hohwille** [comment]
@jomora thanks for your comprehensive investigation.
However, I do not agree in changing the POMs in that way just for the purpose of a workaround.
If we actually have a problem with maven picking the right version for an artifact and two BOMs are conflicting we have to find a better workaround.
I think the build would already work if we just add the version manually in the dependency in our sample. This should be the first try to fix OASP.
However, for external project we should find a way how the archetype produces a ready to use POM.
Maybe we also have to talk to the spring boot BOM maintainers.

**Comment by kiran-vadla** [comment]
@hohwille , We have tried adding flyway 4.x version as a dependency in pom.xml of sample application of OASP4J as a first solution option when we started this migration task and it don't work . Just had a discussion with Jonas (Molina Ramirez, Jonas). He said he will try this option in his machine and get back. 
Thanks , 
Kiran.

**Comment by kiran-vadla** [comment]
@hohwille , @jomora was able to implement your proposal i.e., adding flyway version 4.0.2 manually in the dependency in sample-core. I had a chat with @GawandeKunal as well and came to know that he was also able to implement your proposal earlier itself when we had started the flyway migration . 

In the discussions that we had with @ivanderk , it was suggested by Iwan that version had to be ideally part of pom.xml of OASP4J BOM . So, we have mentioned the version accordingly in pom.xml of OASP4J BOM and we had to shuffle the dependencies of Spring Boot BOM and OASP4J BOM in pom.xml of samples project for the flyway version 4.0.2 to be recognized instead of 3.x. 

In Both the cases/proposals that we have mentioned above , we receive the error https://github.com/flyway/flyway/issues/1352 . 

Thanks,
Kiran.

**Comment by jomora** [comment]
@kiran-vadla @hohwille I looked again at the description of Maven's [dependency mechanism](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html), and I found that I overlooked an important sentence :

> In the example above Z imports the managed dependencies from both X and Y. However, both X and Y contain dependency a. Here, version 1.1 of a would be used since X is declared first and a is not declared in Z's dependencyManagement.

It seems that the behaviour we observed is actually correct. This means that the order of imported POMs in the `oasp4j-samples` POM __does have an impact on the dependencies__. Hence, the solution for our problem is simply to list our own BOM first in the `dependencyManagement` section of `oasp4j-samples` POM.

Nevertheless, by adhering to [the structure I proposed above](https://github.com/oasp/oasp4j/issues/459#issuecomment-242321814) we could avoid this issue.

**Comment by jomora** [comment]
@kiran-vadla It would be awesome if (together with your fix) you could add a comment to the `dependencyManagement` section of the `oasp4j-sample` POM which explains the peculiarities of the order of dependencies. The reader 

1.  should be warned that the order is important, and
2. should be asked to always put the `oasp4j-bom` as the first dependency (this will force OASP dependencies to be favoured about those declared in subsequently declared BOMs)

Thanks :)

**Comment by kiran-vadla** [comment]
@GawandeKunal ,

Please see the comments from @jomora and do the needful. @

Thanks,
Kiran.

**Comment by GawandeKunal** [comment]
@jomora , @kiran-vadla 

I have added mentioned necessary comment to the  dependency management section of the oasp4j-samples POM . 

Reference URL : https://github.com/GawandeKunal/oasp4j/tree/develop/samples

Thanks
Kunal

**Comment by geoffroya** [comment]
Hi

We applied proposed solution to use Flyway 4.2.0 with OASP 2.2 and 2.4. ie Our root project is not child of OASP
Would you like a PR for 2.4.0 ?

Best regards

Geoffroy

**Comment by geoffroya** [comment]
PR is here: https://github.com/oasp/oasp4j/pull/600
Sorry for not following git commit message format - I saw rules afterwards...

**Comment by hohwille** [comment]
Meanwhile we should talk about flyway 5.x
However, we might also need to pull out a oasp4j release 2.x using flyway 4.1 while 3.0 (eve) comes with flyway 5.x. This is necessary as there is no direct upgrade path from flyway 3 to 5 (pity).

**Comment by AbhayChandel** [comment]
This is covered in #620 and can be closed with it.

**Comment by hohwille** [comment]
oasp4j 2.6.x --> Flyway 4
oasp4j 3.0.x --> Flyway 5
