### ISSUE TITLE
get current user and her role

### ISSUE THREAD

**Issue by darkmanAmazigh** [oasp/oasp4j#525]
how to get the currentuser and her role using osap4j ?
i can get them with this

       model.addObject("role", UserData.get().toClientTo().getRole());

Thank you

**Comment by jomora** [comment]
@darkmanAmazigh, questions regarding the usage of the API, e.g. how to fetch the current user or how to do something else, are not considered to be technical/functional issues. Please, ask such questions only on Yammer.

One hint: your code snippet is incomplete and not easy to understand. If you ask such questions, they should be more detailed, e.g. the type of `model` is not obvious and should be somehow indicated.

Closed due to invalid!

**Comment by hohwille** [comment]
We are using Spring Security so to get the user and roles the most robust and reliable way is to use `SecurityContextHolder`. The roles are the `GrantedAuthority` objects in the `Authentication`.

However, if you are using OASP your way to go via `UserData.get()` is also OK but you should avoid using `toClientTo()` just to get the roles.
