### ISSUE TITLE
Override AbstractGenericDao#getEntityManager()

### ISSUE THREAD

**Issue by mathieu-lavigne** [oasp/oasp4j#542]
It is not possible to override AbstractGenericDao#getEntityManager() with your own code because sometimes this class uses its getter and sometimes its field directly.

Could it possible to replace each occurence of this :

```java
this.entityManager
```

by that ?

```java
getEntityManager()
```

@geoffroya

**Comment by jomora** [comment]
In general: 
You found a good one there :-) If you want you can implement a solution yourself and propose it via a pull request.
Have a look at our [contribution guide](https://github.com/oasp/oasp4j/wiki/oasp-code-contributions).
If you have any questions don't hesitate to ask :-)

Regarding the possible solution:
I would prefer to work with the getter-call instead of the bare attribute, because we don't know if anyone has already implemented a subclass. Using only the attribute and removing the getter could possibly lead to problems in extending subclasses.

_However, could you please provide a code snippet that shows where the problem occurrs?_

Thanks!

**Comment by geoffroya** [comment]
Hi

The bug occurs in a context where we need to address distinct but identical database schemas. Sort of data partitioning required by our business case.
We are developping our generic DAO, tha will be able to find the right EntityManager through its ```getEntityManager()``` method, so we can still take advantage of OASP dataaccess layer.

Best regards

Geoff

**Comment by hohwille** [comment]
PR had already been merged and properly fixes the issue. So I am closing this.
