### ISSUE TITLE
Faulty implementation of equals methods

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#55]
For more context see oasp/oasp4j-sample#37.

Well, yes there is a check in EntityTo class of mmm-util-core-5.0.0, but I would guess that these equals implementation will not work properly. Here the first lines until the class check: 

```java
    if (this == obj) {
      return true;
    }
    if (!super.equals(obj)) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
```

You see that super will be called also here in EntityTo. I searched in the type hierarchy of EntityTo for the next super implementation of equals and I found the Object's equals() implementation. As far as I know the equals implemenation only compares the objects reference like `this == obj`.
So your equals will always return false, when you try to compare two different objects.

**Comment by maihacke** [comment]
Implementing HashCode does hurt very often. If an entity is used in sets, after changing a single property all maps, where this entity is inside - are heavily broken. Since use have to implement equals and hashcode togehter, I strongly vote for just not implement them.
I had many problems in projects where there was a (generated) implementation, but had never a single problem, when there was just the default object implementation.

**Comment by hohwille** [comment]
I have done projects with the opposite experience. This seems to be not an easy one. We should either collect more details here (or in a rationale wiki page) or have a meeting about this.
If we are implementing equals and hashCode we should use Java7 features and not the ugly Eclipse default generated crap.

**Comment by hohwille** [comment]
BTW: The general question is if equals should behave technical or logical. However one can always use (x == x) for identity check and does not need x.equals(x) then.

**Comment by hohwille** [comment]
Created #241 for discussion. This issue is invalid and should stay closed.
