### ISSUE TITLE
Introduce new oasp4j-minimal-bom to manage only oasp4j-* modules (without thirdparty)

### ISSUE THREAD

**Issue by jomora** [oasp/oasp4j#551]
Tasks
* [x] move oasp4j dependencies from `oasp4j-bom` to new `oasp4j-minimal-bom`
* [x] remove `mmm-util-bom` from `oasp4j-bom` (https://github.com/oasp/oasp4j/blob/develop/bom/pom.xml#L33) and instead add the required `mmm-util-*` dependencies (https://github.com/m-m-m/util/blob/master/bom/pom.xml#L116) manually to dependency-management. See comment below about spring-test for further details on this.

@hohwille proposed to introduce an `oasp4j-minimal-bom` which would be used by the actual `oasp4j-bom`.
The `oasp4j-minimal-bom` should manage all OASP4J modules and only those.
By including the `oasp4j-minimal-bom` in the `oasp4j-bom` the latter would still behave as always.

However, projects which use OASP4J could relinquish using `oasp4j-bom` which contains additional dependencies on APIs extraneous to OASP4J, e.g. 
```xml
      <dependency>
        <groupId>org.glassfish.web</groupId>
        <artifactId>javax.el</artifactId>
        <version>2.2.6</version>
      </dependency>
```
(Random dependency)
*Clarification hint:* A BOM is only managing versions of dependencies. So if a project is using the dependency then the BOM will decide which version is used by default (if not explicitly overridden in your project POM).

Thereby, projects would gain the freedom to include OASP4J dependencies AND additional 3rd party APIs without clashing with those defined `oasp4j-bom`.

In general, `oasp4j-bom` will still be a good way to start a new project. For an existing project, however, the better way would be to introduce as few additional dependencies as possible. Therefore, an `oasp4j-minimal-bom` containing only the OASP4J modules would be helpful for such projects.

**Comment by amarinso** [comment]
Won't it be more clear if we call `app-bom` to the file that the application can customize for their needs and it includes by default the dependency to the oasp4j-bom?

For me oasp4j-core-bom seems misleading... wait core? are there other oasp4j-xx-boms?

what do you think?

**Comment by hohwille** [comment]
@amarinso thanks for your feedback. I am fully open to change the name of the new artifact to something better. Consider it as a draft.
Currently we already have `oasp4j-bom` and that name should IMHO not change to keep compatibility and make updating as simple as possible.
For the additional BOM we can discuss. Due to our own naming rules it has to be in the form `oasp4j-*`. Further it should have `-bom` as suffix to indicate that it is a BOM.
> For me oasp4j-core-bom seems misleading... wait core?

I still do not see that `app` would make it more clear or less misleading than `core`.
Maybe a better name would be `oasp4j-minimal-bom` then.

> are there other oasp4j-xx-boms?

Yes, we will have two BOMs that we offer then:
* `oasp4j-bom` is the default one to use OASP4J in the recommended way
* `oasp4j-XXX-bom` is the new BOM that will be introduced and that can be used to use OASP4J but with a different version of spring-boot, etc. if needed. This BOM will only contain versions for `oasp4j` dependencies and not for other thirdparty stuff. The `oasp4j-bom` will import it and mix it with `spring-boot`, etc.

**Comment by hohwille** [comment]
If I upgrade a customer project to oasp4j `2.6.0` and now tests fail with strange exceptions such as
java.lang.ClassNotFoundException: org.springframework.test.context.junit4.SpringRunner

Further investigation is showing that the module was having this dependency chain
`spring-boot-starter-test:1.5.3` -> `spring-test:4.2.6.RELEASE`
The question is why spring-test was downgraded by maven to `4.2.6.RELEASE` (what actually is missing the SpringRunner class).
This is because of an issue with oasp4j-bom that itself imports an old version of mmm bom what is again importing the old spring bom.
In the end spring bom is imported multiple times but the "last" import declaration wins (even though it is wrong and downgrades the version).

I strongly vote to not postpone this issue #551 again and put energy into integrating this into oasp4j 3.0.0.
Further I would also propose to decouple stronger from thirdparty BOMs due to the lack of control. Therefore we should also remove mmm bom from from oasp4j-bom itself and only define the few mmm dependencies to dependency-management manually that we actually use. We could even reduce this down to `mmm-util-core` if we wanted to as the entity interfaces have been extracted to separate modules as requested by oasp4j community ages ago.
However, to me the only important thing is that we should never depend on the versions of spring from third-party libs other than spring itself. Also this BOM and dependency-management cascades have turned out into a monster and "regular humans" might not be able anymore to trace such problems down to the root. I myself can't even tell you right now why this error did not show up earlier.

**Comment by hohwille** [comment]
@AbhayChandel thanks for merging PR #623. I therefore close this issue now.
