### ISSUE TITLE
Duplicate AdvancedRevisionEntity breaks jpa-envers module

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#595]
This bug is breaking the 2.4.0 release!

Currently there are two classes of AdvancedRevisionEntity:
https://github.com/oasp/oasp4j/blob/20b2865a7ce6712fad198e264d71c605a371beaf/modules/jpa-envers/src/main/java/io/oasp/module/jpa/dataaccess/api/common/AdvancedRevisionEntity.java
https://github.com/oasp/oasp4j/blob/20b2865a7ce6712fad198e264d71c605a371beaf/modules/jpa-envers/src/main/java/io/oasp/module/jpa/dataaccess/api/AdvancedRevisionEntity.java

* [ ] Both are registered in the spring context using `@RevisionEntity`, which will break each spring context on launch. 
* [ ] Furthermore, the new (non-deprecated) version is in a common package, which does not match the oasp4j naming conventions. 'common' is equivalent to a layer and should be next to 'dataaccess': https://github.com/oasp/oasp4j/wiki/coding-conventions#packages
So you might want to put it in 'io.oasp.module.jpa.general.dataaccess.api' due to the naming conventions.

**Comment by maybeec** [comment]
closed in favor of #596

**Comment by hohwille** [comment]
See also #595
In case we introduce anything new (new package) we should also consider JDK9 and Jigsaw that will prevent us from split packages what we are currently doing in oasp4j-jpa and oasp4j-jpa-envers. Otherwise ignore this and we will have to take care when JDK9 module support comes into play (if ever).
